### PR TITLE
321 receive page cut off on ipad

### LINKED ISSUE #321: Receive page cut off on an iPad
iPad Pro 6th generation 
Simulator Screen Shot - iPad (6th generation) - 2019-04-07 at 16 42 41

### PR DESCRIPTION
**Pull request by emmanuelkehinde**
Closes #321

### CODE REVIEW

**Comment by zennymorh** [comment]
Fixed

Simulator Screen Shot - iPad (6th generation) - 2019-04-24 at 03 52 01
Simulator Screen Shot - iPhone 5s - 2019-04-24 at 03 52 06

**Comment by emmanuelkehinde** [comment]
Fixed

iPad
Simulator Screen Shot - iPad (6th generation) - 2019-04-24 at 03 52 01

 iPhone 5s
Simulator Screen Shot - iPhone 5s - 2019-04-24 at 03 52 06

**Comment by itswisdomagain** [comment]
> 1. Too much space on iPhone XR
> 
> 

This isn't fixed.

**Comment by itswisdomagain** [comment]
Completed in #342.

**Pull request closed without merging**
